# Generated by Django 4.2.4 on 2023-08-18 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=100000)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 8, 18, 20, 23, 44, 189398))),
            ],
        ),
    ]
